// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WSADFinalProject.Models;

namespace WSADFinalProject.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20210421211530_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WSADFinalProject.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IngredientName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            IngredientName = "onion"
                        },
                        new
                        {
                            IngredientId = 2,
                            IngredientName = "carrots"
                        },
                        new
                        {
                            IngredientId = 3,
                            IngredientName = "garlic cloves"
                        },
                        new
                        {
                            IngredientId = 4,
                            IngredientName = "bay leaf"
                        },
                        new
                        {
                            IngredientId = 5,
                            IngredientName = "butter"
                        },
                        new
                        {
                            IngredientId = 6,
                            IngredientName = "olive oil"
                        },
                        new
                        {
                            IngredientId = 7,
                            IngredientName = "pumpkin"
                        },
                        new
                        {
                            IngredientId = 8,
                            IngredientName = "potato"
                        },
                        new
                        {
                            IngredientId = 9,
                            IngredientName = "chicken stock"
                        },
                        new
                        {
                            IngredientId = 10,
                            IngredientName = "double cream"
                        },
                        new
                        {
                            IngredientId = 11,
                            IngredientName = "pumpkin seeds"
                        },
                        new
                        {
                            IngredientId = 12,
                            IngredientName = "salt"
                        },
                        new
                        {
                            IngredientId = 13,
                            IngredientName = "pepper"
                        },
                        new
                        {
                            IngredientId = 14,
                            IngredientName = "plain flour"
                        },
                        new
                        {
                            IngredientId = 15,
                            IngredientName = "caster sugar"
                        },
                        new
                        {
                            IngredientId = 16,
                            IngredientName = "baking powder"
                        },
                        new
                        {
                            IngredientId = 17,
                            IngredientName = "cocoa powder"
                        },
                        new
                        {
                            IngredientId = 18,
                            IngredientName = "bicarbonate of soda"
                        },
                        new
                        {
                            IngredientId = 19,
                            IngredientName = "eggs"
                        },
                        new
                        {
                            IngredientId = 20,
                            IngredientName = "milk"
                        },
                        new
                        {
                            IngredientId = 21,
                            IngredientName = "vegetable oil"
                        },
                        new
                        {
                            IngredientId = 22,
                            IngredientName = "vanilla"
                        },
                        new
                        {
                            IngredientId = 23,
                            IngredientName = "water"
                        });
                });

            modelBuilder.Entity("WSADFinalProject.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RecipeCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecipeCookTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipePrepTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeServings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.HasIndex("RecipeCategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            RecipeCategoryId = "soups",
                            RecipeCookTime = "30 mins to 1 hour",
                            RecipeDesc = "You need to have this delightfully warming pumpkin soup in your little black book of dinners. Serve with a swirl of cream.",
                            RecipeMethod = @"Put the onion, carrots, garlic bay leaf, butter and half the olive oil into a large pan. Cook over a low–medium heat for about 10 minutes until the vegetables are tender but not coloured. 
 Add the squash and potato, mix to combine and cook for a further 2–3 minutes. Pour in the stock, season well and bring to the boil. Reduce the heat to a gentle simmer, half cover the pan with a lid and continue to cook for about 40 minutes until the squash is really tender when tested with the point of a knife. 
 Pick out the bay leaf and blend the soup until smooth using a stick blender. 
 Add the cream and a little more stock if the soup is on the thick side, taste for seasoning, adding more salt and pepper as required. 
 Meanwhile, heat the remaining oil in a frying pan over a medium heat and add the pumpkin seeds and fry quickly until the seeds start to pop. Remove from the pan. 
 Ladle the soup into bowls and serve with a swirl of cream and the toasted pumpkin seeds.",
                            RecipeName = "Pumpkin Soup",
                            RecipePrepTime = "less than 30 mins",
                            RecipeServings = "Serves 6–8"
                        },
                        new
                        {
                            RecipeId = 2,
                            RecipeCategoryId = "desserts",
                            RecipeCookTime = "30 mins to 1 hour",
                            RecipeDesc = "Our really easy chocolate cake recipe is moist and fudgy and will keep well for 4–5 days.",
                            RecipeMethod = @"Preheat the oven to 180C/160C Fan/Gas 4. Grease and line two 20cm/8in sandwich tins.
 For the cake, place all of the cake ingredients, except the boiling water, into a large mixing bowl. Using a wooden spoon, or electric whisk, beat the mixture until smooth and well combined. 
 Add the boiling water to the mixture, a little at a time, until smooth. (The cake mixture will now be very liquid.) 
 Divide the cake batter between the sandwich tins and bake in the oven for 25–35 minutes, or until the top is firm to the touch and a skewer inserted into the centre of the cake comes out clean. 
 Remove the cakes from the oven and allow to cool completely, still in their tins, before icing. 
 For the chocolate icing, heat the chocolate and cream in a saucepan over a low heat until the chocolate melts. Remove the pan from the heat and whisk the mixture until smooth, glossy and thickened. Set aside to cool for 1–2 hours, or until thick enough to spread over the cake. 
 To assemble the cake, run a round-bladed knife around the inside of the cake tins to loosen the cakes. Carefully remove the cakes from the tins. 
 Spread a little chocolate icing over the top of one of the chocolate cakes, then carefully top with the other cake. 
 Transfer the cake to a serving plate and ice the cake all over with the chocolate icing, using a palette knife.",
                            RecipeName = "Chocolate Cake",
                            RecipePrepTime = "less than 30 mins",
                            RecipeServings = "Serves 12"
                        });
                });

            modelBuilder.Entity("WSADFinalProject.Models.RecipeCategory", b =>
                {
                    b.Property<string>("RecipeCategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RecipeCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeCategoryId");

                    b.ToTable("RecipeCategorys");

                    b.HasData(
                        new
                        {
                            RecipeCategoryId = "breakfast",
                            RecipeCategoryName = "Breakfast"
                        },
                        new
                        {
                            RecipeCategoryId = "lunch",
                            RecipeCategoryName = "Lunch"
                        },
                        new
                        {
                            RecipeCategoryId = "beverages",
                            RecipeCategoryName = "Beverages"
                        },
                        new
                        {
                            RecipeCategoryId = "appetizers",
                            RecipeCategoryName = "Appetizers"
                        },
                        new
                        {
                            RecipeCategoryId = "soups",
                            RecipeCategoryName = "Soups"
                        },
                        new
                        {
                            RecipeCategoryId = "salads",
                            RecipeCategoryName = "Salads"
                        },
                        new
                        {
                            RecipeCategoryId = "mandishes",
                            RecipeCategoryName = "Main dishes"
                        },
                        new
                        {
                            RecipeCategoryId = "desserts",
                            RecipeCategoryName = "Desserts"
                        },
                        new
                        {
                            RecipeCategoryId = "bread",
                            RecipeCategoryName = "Bread"
                        },
                        new
                        {
                            RecipeCategoryId = "vegetarian",
                            RecipeCategoryName = "Vegetarian"
                        });
                });

            modelBuilder.Entity("WSADFinalProject.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("IngredientQty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 1,
                            IngredientQty = "1"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 2,
                            IngredientQty = "2"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 3,
                            IngredientQty = "2"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 4,
                            IngredientQty = "1"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 5,
                            IngredientQty = "25g"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 6,
                            IngredientQty = "2T"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 7,
                            IngredientQty = "1"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 8,
                            IngredientQty = "1"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 9,
                            IngredientQty = "1l"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 10,
                            IngredientQty = "100ml"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 11,
                            IngredientQty = "3T"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 12,
                            IngredientQty = "pinch"
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 13,
                            IngredientQty = "pinch"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 14,
                            IngredientQty = "225g"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 15,
                            IngredientQty = "350g"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 16,
                            IngredientQty = "85g"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 17,
                            IngredientQty = "1.5t"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 18,
                            IngredientQty = "1.5t"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 19,
                            IngredientQty = "2"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 20,
                            IngredientQty = "250ml"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 21,
                            IngredientQty = "125ml"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 22,
                            IngredientQty = "2t"
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 23,
                            IngredientQty = "250ml"
                        });
                });

            modelBuilder.Entity("WSADFinalProject.Models.Recipe", b =>
                {
                    b.HasOne("WSADFinalProject.Models.RecipeCategory", "RecipeCategory")
                        .WithMany("Recipes")
                        .HasForeignKey("RecipeCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WSADFinalProject.Models.RecipeIngredient", b =>
                {
                    b.HasOne("WSADFinalProject.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WSADFinalProject.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
